// Cezalar.jsx

const Cezalar = {
  kolay: [
    "Kazanan yüzüne bir şey çizsin ve öyle bir story paylaşsın.",
    "Karşı cinsten birini seçip, 'Tam uykuya dalarken kakamı şimdi mi yapsam sabah mı diye düşündüğün oluyor mu hiç?' de.",
    "Kazananın seçtiği bir şarkıyı söylerken story paylaş",
    "Herkese pizza ısmarla.",
    "Herkese açık bir sesli sohbette tiz bir sincap sesiyle milli marşı söyleyin.",
    "Oyunun geri kalanında rakiplerine 'tatlım' diye hitap edin.",
    // Yeni kolay cezalar:
    "En sevdiğin şarkıyı en sevmediğin ses tonunda söyleyerek paylaş.",
    "Karşındakine en sevdiği yemeği sipariş etmesini sağla.",
    "Kazananın seçtiği bir kişiye tatlı bir mesaj gönder.",
    "Kazananın seçtiği bir arkadaşını taklit ederek bir hikaye anlat.",
    "Bir çocuk masalını komik bir şekilde yeniden anlatarak videoya kaydet.",
    "Kazananın seçtiği bir arkadaşına en garip selfie'ni gönder.",
    "Karşındaki kişiye en komik hikayeni anlat.",
    "Kazananın seçtiği birine komik bir ses kaydı gönder.",
    "En sevdiğin hayvanın taklidi yaparak videoya kaydet.",
    "Karşındakinin en sevdiği film repliğini taklit et.",
    "Bir şakayı en ciddi halinle anlatarak videoya kaydet.",
    "Kazananın seçtiği birine en güzel dileklerini ileten bir mesaj gönder.",
    "Karşındaki kişiye en sevdiği yemek tarifini sormak için video kaydet.",
    "Bir komik videoyu en ciddi halinle izleyerek paylaş.",
    "En son izlediğin filmi en kötü şekilde anlatarak videoya kaydet.",
    "Karşındakinin seçtiği bir şarkıyı en acemi halinle çal.",
    "Kazananın seçtiği bir arkadaşını en komik haliyle taklit et.",
    "Bir çizgi film karakterini seslendirerek videoya kaydet.",
    "Karşındakinin en sevdiği yemek tarifini kötü bir şekilde uygulayarak videoya kaydet.",
    "Kazananın seçtiği bir arkadaşını en aptal haliyle taklit et.",
    "Bir korku filmi sahnesini komik bir şekilde yeniden canlandırarak videoya kaydet.",
    "Karşındaki kişinin en sevdiği film sahnesini en kötü şekilde canlandırarak videoya kaydet.",
    "En sevdiğin çocuk şarkısını en kötü şekilde söyleyerek videoya kaydet.",
    "En sevdiğin şarkıyı en garip ses tonuyla söyleyerek video paylaş.",
    "Karşındaki kişiye en sevdiği yemek tarifini en komik şekilde anlat.",
    "Kazananın seçtiği bir kişiye komik bir şiir yaz ve oku.",
    "En sevdiğin hayvanın sesini taklit ederek bir hikaye anlatarak video paylaş.",
    "Karşındaki kişiye en sevdiği filmi en kötü şekilde özetle.",
    "Bir şarkıyı en hızlı şekilde söyleyerek video paylaş.",
    "Kazananın seçtiği bir kişiye en komik yüzünü gösteren bir selfie gönder."
  ],
  orta: [
    "Karşındakinin seçtiği herhangi bir sosyal medya hesabındaki profil fotoğrafını karşındakinin resmiyle değiştir.",
    "5 dakika tavuk gibi davran.",
    "Kişi listesindeki rastgele bir kişiyi arayın ve onu elektrikli süpürge almaya ikna edin.",
    "Kazananın kimliğine bürünün ve seçtiği kişiyi arayın.",
    "Kullanıcı adını bir günlüğüne aptalca veya utanç verici bir şeyle değiştirin. (Öneri: Cheeks McClappin, Terli Betty, Respecto Palletonum, Adon Bilivit, Ahmed Sheeran, Amunder Yabed).",
    "TikTok dansı yaparken 10 saniyelik bir video kaydedin ve kazananın seçtiği birine gönderin.",
    "Kazananın seçtiği birinin sosyal medya hesabına övgü dolu yorum bırak.",
    "Çatalla bir şey içerken kazananın seçtiği birini görüntülü arayın.",
    "Ortaokul arkadaşları gibi uzun süredir konuşmadığınız birine mesaj atın ve ondan popo estetiği için borç para isteyin.",
    // Yeni cezalar:
    "Karşındakinin en sevdiği film repliğini taklit et.",
    "Bir TikTok dansı yaparak videoya kaydet ve kazananın seçtiği birine gönder.",
    "En sevdiğin yemek tarifini paylaşarak videoya kaydet.",
    "Bir film sahnesini canlandırarak videoya kaydet.",
    "En komik anını anlatarak videoya kaydet.",
    "Karşındakinin en sevdiği müziği çalacak bir enstrüman çalmaya çalışarak videoya kaydet.",
    "Karşındakinin en sevdiği film karakterini canlandırarak videoya kaydet.",
    "Bir sesli mesaj gönderirken karşındakinin seçtiği bir şarkıyı arka planda çal.",
    "Karşındakinin seçtiği bir hikayeyi komik bir şekilde anlatarak videoya kaydet.",
    "Bir karaoke performansı sergileyerek videoya kaydet.",
    "En sevdiğin şarkıyı farklı bir tarzda söyleyerek videoya kaydet.",
    "Karşındakinin en aptal sorusunu sormak için videoya kaydet.",
    "Kazananın seçtiği bir arkadaşının en komik anını anlatarak videoya kaydet.",
    "En sevdiğin karikatür karakterini en kötü haliyle taklit et.",
    "Karşındakinin seçtiği bir şarkıyı komik bir şekilde yorumla ve videoya kaydet.",
    "En komik şaka anını anlatarak videoya kaydet.",
    "Karşındakinin seçtiği bir hikayeyi en dramatik şekilde anlatarak videoya kaydet.",
    "Kazananın seçtiği bir film karakterinin en kötü taklidini yaparak videoya kaydet.",
    "Bir TikTok trendini en komik şekilde taklit et ve videoya kaydet.",
    "Karşındakinin seçtiği bir ünlüyü taklit et ve videoya kaydet.",
    "En komik karaoke performansını sergileyerek videoya kaydet.",
    "Bir gün boyunca en sevmediğin renkte giyin.",
    "Kazananın seçtiği bir kişinin evine gidip kapıyı çal ve sonra kaç.",
    "5 dakika boyunca telefonla konuşurken sürekli 'pardon?' de.",
    "Kişi listesindeki rastgele bir kişiyi arayın ve ona en sevdiğiniz şakayı anlatın.",
    "Kazananın seçtiği bir kişiye, en sevmediğin yemeği pişirdiğini söyle ve tepkisini videoya kaydet.",
    "Bir film sahnesini en komik şekilde canlandırmaya çalışarak video paylaş.",
    "Kazananın seçtiği bir kişiye komik bir anını anlatan bir sesli mesaj gönder."
  ],
  zor: [
    "Kazananın seçtiği birine 'Sence de artık bana borcunu ödeme zamanı gelmedi mi?' diye mesaj at.",
    "En son konuştuğun insana 'sensiz ne yaparım ben?' diye mesaj at",
    "Tek kaşını tıraş et.",
    "Karşı cins kıyafeti giyip kazananın seçtiği birine video atın.",
    "En son aldığın mesaja 'evet, babuş' diye yanıt ver.",
    "Kazananın seçtiği bir kişiye açık bir sosyal medya platformunda utandırıcı bir anını paylaş.",
    "Karşı cinsten birisine 'Eğer bir deniz kızı olsaydın, kuyruğunun nasıl görüneceğini hayal edebilir misin?' diye sor.",
    "Bir telefon görüşmesinde 'Evet, babam.' diyerek telefonu kapat.",
    "Kazananın seçtiği bir kişiye, komik bir dans videosu gönder.",
    "Kazananın seçtiği birine 'Benim bornozumun sende ne işi var?' diye sor.",
    "Düşük bir tekerleğin üzerinde yürüyerek kazananın seçtiği birinin evine gidin.",
    // Yeni cezalar:
    "Karşındakinin seçtiği bir hikayeyi ti'ye alarak anlatarak videoya kaydet.",
    "Bir karaoke partisine katılın ve kazananın seçtiği bir şarkıyı seslendirin.",
    "En sevdiğiniz film repliğini en ciddi şekilde seslendirerek videoya kaydet.",
    "Karşındakinin seçtiği bir karakterin taklidini yaparak videoya kaydet.",
    "Bir stand-up rutini yaparak videoya kaydet.",
    "Karşındakinin seçtiği bir kıyafeti giyerek videoya kaydet.",
    "Bir kıyafet değişimi videosu kaydederek kazananın seçtiği birine gönder.",
    "Karşındakinin seçtiği bir hikayeyi en dramatik şekilde anlatarak videoya kaydet.",
    "Bir maskeleme videosu yaparak kazananın seçtiği birine gönder.",
    "Karşındakinin en sevdiği film müziğini çalmaya çalışarak videoya kaydet.",
    "En sevdiğiniz kitaptan bir alıntı okuyarak videoya kaydet.",
    "Karşındakinin seçtiği bir hikayeyi ti'ye alarak anlatarak videoya kaydet.",
    "Bir karaoke partisine katılın ve kazananın seçtiği bir şarkıyı seslendirin.",
    "En sevdiğiniz film repliğini en ciddi şekilde seslendirerek videoya kaydet.",
    "Karşındakinin seçtiği bir karakterin taklidini yaparak videoya kaydet.",
    "Bir stand-up rutini yaparak videoya kaydet.",
    "Karşındakinin seçtiği bir kıyafeti giyerek videoya kaydet.",
    "Karşındakinin seçtiği bir hikayeyi en dramatik şekilde anlatarak videoya kaydet.",
    "Bir maskeleme videosu yaparak kazananın seçtiği birine gönder.",
    "Karşındakinin en sevdiği film müziğini çalmaya çalışarak videoya kaydet.",
    "En sevdiğiniz kitaptan bir alıntı okuyarak videoya kaydet.",
    "Kazananın seçtiği bir kişinin evinde bir gece kal.",
    "En son konuştuğun kişiye 'Seni seviyorum' de.",
    "Sokakta en sevdiğin şarkıyı yüksek sesle söyle.",
    "Kazananın seçtiği bir kişiye, onunla asla görüşmeyeceğini söyle.",
    "Bir hafta boyunca her gün en sevmediğin rengi giy.",
    "Kazananın seçtiği bir kişiye, onunla dalga geçen bir şarkı yaz ve söyle.",
    "En son aldığın mesaja 'Ben bir robotum' diye yanıt ver."
  ]
};
  
  export default Cezalar;
  